/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Maxim Mavrichev (https://sketchfab.com/mvrc.art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/meteor-d3a5a7e9a7d24b76841bf0f49d56a5f3
Title: Meteor
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import meteor from  "../assets/3d/meteor.glb"
import { useFrame, useThree } from "@react-three/fiber";

export function MeteorShower(props) {
  const { nodes, materials } = useGLTF(meteor);
  const group = useRef();
  const { size, viewport } = useThree();
  const aspect = size.width / viewport.width;


  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(meteor);
