/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import space from "../assets/3d/need_some_space.glb"
import { useFrame } from "@react-three/fiber";

export function Space(props) {
  const { nodes, materials } = useGLTF(space);
  const spaceRef = useRef();

  useFrame(() => {
    spaceRef.current.rotation.y += 0.005;
  })

  return (
    <group ref={spaceRef} {...props} dispose={null}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </group>
  );
}

useGLTF.preload(space);
